import { useState, useEffect, useRef } from "react";
import { Plus, Pencil, Trash2, Loader2, Save, X, Sparkles, Wand2, Clock, Play } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";
import { BibleGame } from "@/hooks/useBibleGames";
import { useQuestionGenerator } from "@/hooks/useQuestionGenerator";

// Popular Bible stories for story-based question generation
const BIBLE_STORIES = [
  { value: "Creation", label: "Creation & Garden of Eden", testament: "old" },
  { value: "Noah's Ark", label: "Noah's Ark - The Flood", testament: "old" },
  { value: "Abraham", label: "Abraham & Isaac", testament: "old" },
  { value: "Moses", label: "Moses & The Exodus", testament: "old" },
  { value: "Ten Plagues", label: "Ten Plagues of Egypt", testament: "old" },
  { value: "David and Goliath", label: "David and Goliath", testament: "old" },
  { value: "Samson", label: "Samson", testament: "old" },
  { value: "Jonah", label: "Jonah", testament: "old" },
  { value: "Job", label: "Job", testament: "old" },
  { value: "Solomon", label: "Solomon's Wisdom", testament: "old" },
  { value: "Jesus Birth", label: "Jesus' Birth", testament: "new" },
  { value: "Jesus Miracles", label: "Jesus' Miracles", testament: "new" },
  { value: "Sermon on the Mount", label: "Sermon on the Mount", testament: "new" },
  { value: "Parables", label: "Jesus' Parables", testament: "new" },
  { value: "Last Supper", label: "The Last Supper", testament: "new" },
  { value: "Crucifixion", label: "Crucifixion & Resurrection", testament: "new" },
  { value: "Pentecost", label: "Pentecost & Holy Spirit", testament: "new" },
  { value: "Peter", label: "Peter's Journey", testament: "new" },
  { value: "Paul", label: "Paul's Conversion & Ministry", testament: "new" },
  { value: "Epistles", label: "Paul's Epistles", testament: "new" },
];

const AdminGameManagement = () => {
  const [games, setGames] = useState<BibleGame[]>([]);
  const [loading, setLoading] = useState(true);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingGame, setEditingGame] = useState<BibleGame | null>(null);
  const [saving, setSaving] = useState(false);
  const [generateCount, setGenerateCount] = useState(3);
  const [generateStory, setGenerateStory] = useState<string>(''); // Story or random
  const [generateTestament, setGenerateTestament] = useState<'old' | 'new' | ''>(''); // Testament filter
  const { generateQuestions, isGenerating } = useQuestionGenerator();
  const [filterType, setFilterType] = useState<'all' | BibleGame['game_type']>('all');
  const autoGeneratedRef = useRef(new Set<string>());
  const [deletingFiltered, setDeletingFiltered] = useState(false);
  
  // Cleanup settings state
  const [cleanupDays, setCleanupDays] = useState(3);
  const [savingCleanup, setSavingCleanup] = useState(false);
  const [runningCleanup, setRunningCleanup] = useState(false);
  // Form state
  const [formData, setFormData] = useState({
    game_type: 'trivia' as BibleGame['game_type'],
    question: '',
    options: ['', '', '', ''],
    correct_answer: '',
    hint: '',
    difficulty: 'medium' as BibleGame['difficulty'],
    bible_reference: '',
    points: 10,
    is_active: true
  });

  const fetchGames = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('bible_games')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw error;

      if (data) {
        setGames(data.map(game => ({
          ...game,
          options: game.options as string[] | null,
          game_type: game.game_type as BibleGame['game_type'],
          difficulty: game.difficulty as BibleGame['difficulty']
        })));
      }
    } catch (error) {
      console.error('Error fetching games:', error);
      toast({
        title: "Error",
        description: "Failed to load games",
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchGames();
    fetchCleanupSettings();
  }, []);

  // After fetchGames completes, check for empty categories and auto-generate once per category
  useEffect(() => {
    if (!loading) {
      const counts = {
        trivia: games.filter(g => g.game_type === 'trivia').length,
        guess_character: games.filter(g => g.game_type === 'guess_character').length,
        fill_blank: games.filter(g => g.game_type === 'fill_blank').length,
        memory_verse: games.filter(g => g.game_type === 'memory_verse').length,
      } as Record<string, number>;

      (Object.keys(counts) as Array<keyof typeof counts>).forEach(async (key) => {
        if (counts[key] === 0 && !autoGeneratedRef.current.has(key)) {
          autoGeneratedRef.current.add(key);
          try {
            await generateQuestions(key as any, generateCount);
            await fetchGames();
            toast({ title: 'Auto-generated', description: `Generated ${generateCount} ${key} questions because none existed.` });
          } catch (e) {
            console.error('Auto-generate failed for', key, e);
          }
        }
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading, games]);

  const fetchCleanupSettings = async () => {
    try {
      const { data, error } = await supabase
        .from('app_settings')
        .select('value')
        .eq('key', 'bible_questions_cleanup_age')
        .maybeSingle();

      if (data?.value && typeof data.value === 'object' && 'days' in data.value) {
        setCleanupDays((data.value as { days: number }).days);
      }
    } catch (error) {
      console.error('Error fetching cleanup settings:', error);
    }
  };

  const handleSaveCleanupSettings = async () => {
    setSavingCleanup(true);
    try {
      const { error } = await supabase
        .from('app_settings')
        .upsert({
          key: 'bible_questions_cleanup_age',
          value: { days: cleanupDays }
        }, { onConflict: 'key' });

      if (error) throw error;

      toast({
        title: "Saved",
        description: `Questions older than ${cleanupDays} days will be auto-deleted`
      });
    } catch (error) {
      console.error('Error saving cleanup settings:', error);
      toast({
        title: "Error",
        description: "Failed to save cleanup settings",
        variant: "destructive"
      });
    } finally {
      setSavingCleanup(false);
    }
  };

  const handleRunCleanup = async () => {
    setRunningCleanup(true);
    try {
      const { error } = await supabase.rpc('delete_old_bible_questions');

      if (error) throw error;

      toast({
        title: "Cleanup Complete",
        description: "Old questions have been deleted"
      });
      fetchGames();
    } catch (error) {
      console.error('Error running cleanup:', error);
      toast({
        title: "Error",
        description: "Failed to run cleanup",
        variant: "destructive"
      });
    } finally {
      setRunningCleanup(false);
    }
  };

  const resetForm = () => {
    setFormData({
      game_type: 'trivia',
      question: '',
      options: ['', '', '', ''],
      correct_answer: '',
      hint: '',
      difficulty: 'medium',
      bible_reference: '',
      points: 10,
      is_active: true
    });
    setEditingGame(null);
  };

  const handleEdit = (game: BibleGame) => {
    setEditingGame(game);
    setFormData({
      game_type: game.game_type,
      question: game.question,
      options: game.options || ['', '', '', ''],
      correct_answer: game.correct_answer,
      hint: game.hint || '',
      difficulty: game.difficulty,
      bible_reference: game.bible_reference || '',
      points: game.points,
      is_active: game.is_active
    });
    setDialogOpen(true);
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Are you sure you want to delete this game?')) return;

    try {
      const { error } = await supabase
        .from('bible_games')
        .delete()
        .eq('id', id);

      if (error) throw error;

      toast({
        title: "Deleted",
        description: "Game deleted successfully"
      });
      fetchGames();
    } catch (error) {
      console.error('Error deleting game:', error);
      toast({
        title: "Error",
        description: "Failed to delete game",
        variant: "destructive"
      });
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);

    try {
      const gameData = {
        game_type: formData.game_type,
        question: formData.question,
        options: formData.options.filter(o => o.trim() !== ''),
        correct_answer: formData.correct_answer,
        hint: formData.hint || null,
        difficulty: formData.difficulty,
        bible_reference: formData.bible_reference || null,
        points: formData.points,
        is_active: formData.is_active
      };

      if (editingGame) {
        const { error } = await supabase
          .from('bible_games')
          .update(gameData)
          .eq('id', editingGame.id);

        if (error) throw error;
        toast({ title: "Updated", description: "Game updated successfully" });
      } else {
        const { error } = await supabase
          .from('bible_games')
          .insert(gameData);

        if (error) throw error;
        toast({ title: "Created", description: "Game created successfully" });
      }

      setDialogOpen(false);
      resetForm();
      fetchGames();
    } catch (error) {
      console.error('Error saving game:', error);
      toast({
        title: "Error",
        description: "Failed to save game",
        variant: "destructive"
      });
    } finally {
      setSaving(false);
    }
  };

  const updateOption = (index: number, value: string) => {
    const newOptions = [...formData.options];
    newOptions[index] = value;
    setFormData({ ...formData, options: newOptions });
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  const handleGenerateQuestions = async (gameType: "trivia" | "guess_character" | "fill_blank" | "memory_verse") => {
    const options: any = {};
    if (generateStory) {
      options.bible_story = generateStory;
    } else if (generateTestament) {
      options.testament = generateTestament;
    }
    
    const result = await generateQuestions(gameType, generateCount, options);
    if (result?.success) {
      fetchGames();
    }
  };

  const triviaCount = games.filter(g => g.game_type === 'trivia').length;
  const characterCount = games.filter(g => g.game_type === 'guess_character').length;
  const fillBlankCount = games.filter(g => g.game_type === 'fill_blank').length;
  const memoryVerseCount = games.filter(g => g.game_type === 'memory_verse').length;

  return (
    <div className="space-y-6">
      {/* AI Question Generation Section */}
      <Card className="bg-gradient-to-br from-primary/10 via-primary/5 to-background border-primary/20">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-lg">
            <Sparkles className="w-5 h-5 text-primary" />
            AI Question Generator
          </CardTitle>
          <CardDescription>
            Generate new Bible game questions using AI. Questions are automatically saved to the database.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="flex items-center gap-4">
              <Label className="whitespace-nowrap">Questions per type:</Label>
              <Select
                value={generateCount.toString()}
                onValueChange={(value) => setGenerateCount(parseInt(value))}
              >
                <SelectTrigger className="w-24">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="1">1</SelectItem>
                  <SelectItem value="3">3</SelectItem>
                  <SelectItem value="5">5</SelectItem>
                  <SelectItem value="10">10</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label className="text-sm">Bible Story (optional)</Label>
              <Select
                value={generateStory}
                onValueChange={(value) => {
                  setGenerateStory(value === 'none' ? '' : value);
                  setGenerateTestament(''); // Clear testament when choosing a story
                }}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select a story" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">Random Story</SelectItem>
                  {BIBLE_STORIES.map(story => (
                    <SelectItem key={story.value} value={story.value}>
                      {story.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label className="text-sm">Testament Filter (if no story)</Label>
              <Select
                value={generateTestament}
                onValueChange={(value) => {
                  setGenerateTestament(value as 'old' | 'new' | '');
                  if (value) setGenerateStory(''); // Clear story when choosing testament
                }}
                disabled={!!generateStory}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Any testament" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="">Any Testament</SelectItem>
                  <SelectItem value="old">Old Testament</SelectItem>
                  <SelectItem value="new">New Testament</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-3">
            <Button
              onClick={() => handleGenerateQuestions("trivia")}
              disabled={isGenerating}
              variant="outline"
              className="gap-2 h-auto py-3 flex-col items-start"
            >
              <div className="flex items-center gap-2 w-full">
                {isGenerating ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Wand2 className="w-4 h-4" />
                )}
                <span className="font-medium">Generate Trivia</span>
              </div>
              <span className="text-xs text-muted-foreground">
                {triviaCount} existing questions
              </span>
            </Button>

            <Button
              onClick={() => handleGenerateQuestions("guess_character")}
              disabled={isGenerating}
              variant="outline"
              className="gap-2 h-auto py-3 flex-col items-start"
            >
              <div className="flex items-center gap-2 w-full">
                {isGenerating ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Wand2 className="w-4 h-4" />
                )}
                <span className="font-medium">Generate Characters</span>
              </div>
              <span className="text-xs text-muted-foreground">
                {characterCount} existing questions
              </span>
            </Button>

            <Button
              onClick={() => handleGenerateQuestions("fill_blank")}
              disabled={isGenerating}
              variant="outline"
              className="gap-2 h-auto py-3 flex-col items-start"
            >
              <div className="flex items-center gap-2 w-full">
                {isGenerating ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Wand2 className="w-4 h-4" />
                )}
                <span className="font-medium">Generate Fill-in-the-Blank</span>
              </div>
              <span className="text-xs text-muted-foreground">
                {fillBlankCount} existing questions
              </span>
            </Button>

            <Button
              onClick={() => handleGenerateQuestions("memory_verse")}
              disabled={isGenerating}
              variant="outline"
              className="gap-2 h-auto py-3 flex-col items-start"
            >
              <div className="flex items-center gap-2 w-full">
                {isGenerating ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Wand2 className="w-4 h-4" />
                )}
                <span className="font-medium">Generate Memory Verses</span>
              </div>
              <span className="text-xs text-muted-foreground">
                {memoryVerseCount} existing questions
              </span>
            </Button>
          </div>

          {isGenerating && (
            <div className="flex items-center gap-2 text-sm text-primary animate-pulse">
              <Sparkles className="w-4 h-4" />
              AI is generating {generateCount} new questions...
            </div>
          )}
        </CardContent>
      </Card>

      {/* Auto-Cleanup Settings */}
      <Card className="bg-card border-border">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-lg">
            <Clock className="w-5 h-5 text-muted-foreground" />
            Auto-Cleanup Settings
          </CardTitle>
          <CardDescription>
            Automatically delete old questions to keep the game content fresh
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center gap-3">
            <Label className="text-sm">Delete questions older than:</Label>
            <div className="flex items-center gap-2 flex-wrap">
              <Select
                value={cleanupDays.toString()}
                onValueChange={(value) => setCleanupDays(parseInt(value))}
              >
                <SelectTrigger className="w-28">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="1">1 day</SelectItem>
                  <SelectItem value="3">3 days</SelectItem>
                  <SelectItem value="5">5 days</SelectItem>
                  <SelectItem value="7">7 days</SelectItem>
                  <SelectItem value="14">14 days</SelectItem>
                  <SelectItem value="30">30 days</SelectItem>
                </SelectContent>
              </Select>
              <Button 
                onClick={handleSaveCleanupSettings} 
                disabled={savingCleanup}
                size="sm"
              >
                {savingCleanup ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Save className="w-4 h-4 mr-1" />
                )}
                Save
              </Button>
              <Button 
                onClick={handleRunCleanup} 
                disabled={runningCleanup}
                size="sm"
                variant="outline"
              >
                {runningCleanup ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Play className="w-4 h-4 mr-1" />
                )}
                Run Now
              </Button>
            </div>
          </div>
          <p className="text-xs text-muted-foreground">
            Cleanup runs automatically every day at midnight
          </p>
        </CardContent>
      </Card>

      {/* Existing Games Section */}
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold">Bible Games ({games.length})</h2>
        <Dialog open={dialogOpen} onOpenChange={(open) => {
          setDialogOpen(open);
          if (!open) resetForm();
        }}>
          <DialogTrigger asChild>
            <Button size="sm" className="gap-2">
              <Plus className="w-4 h-4" />
              Add Game
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>{editingGame ? 'Edit Game' : 'Add New Game'}</DialogTitle>
            </DialogHeader>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Game Type</Label>
                  <Select
                    value={formData.game_type}
                    onValueChange={(value: BibleGame['game_type']) => 
                      setFormData({ ...formData, game_type: value })
                    }
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="trivia">Trivia</SelectItem>
                      <SelectItem value="guess_character">Guess Character</SelectItem>
                      <SelectItem value="fill_blank">Fill in Blank</SelectItem>
                      <SelectItem value="memory_verse">Memory Verse</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Difficulty</Label>
                  <Select
                    value={formData.difficulty}
                    onValueChange={(value: BibleGame['difficulty']) => 
                      setFormData({ ...formData, difficulty: value })
                    }
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="easy">Easy</SelectItem>
                      <SelectItem value="medium">Medium</SelectItem>
                      <SelectItem value="hard">Hard</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="space-y-2">
                <Label>Question</Label>
                <Textarea
                  value={formData.question}
                  onChange={(e) => setFormData({ ...formData, question: e.target.value })}
                  required
                  rows={3}
                />
              </div>

              <div className="space-y-2">
                <Label>Options (for multiple choice)</Label>
                <div className="space-y-2">
                  {formData.options.map((option, index) => (
                    <Input
                      key={index}
                      value={option}
                      onChange={(e) => updateOption(index, e.target.value)}
                      placeholder={`Option ${index + 1}`}
                    />
                  ))}
                </div>
              </div>

              <div className="space-y-2">
                <Label>Correct Answer</Label>
                <Input
                  value={formData.correct_answer}
                  onChange={(e) => setFormData({ ...formData, correct_answer: e.target.value })}
                  required
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Bible Reference</Label>
                  <Input
                    value={formData.bible_reference}
                    onChange={(e) => setFormData({ ...formData, bible_reference: e.target.value })}
                    placeholder="e.g., John 3:16"
                  />
                </div>
                <div className="space-y-2">
                  <Label>Points</Label>
                  <Input
                    type="number"
                    value={formData.points}
                    onChange={(e) => setFormData({ ...formData, points: parseInt(e.target.value) || 10 })}
                    min={1}
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label>Hint (optional)</Label>
                <Input
                  value={formData.hint}
                  onChange={(e) => setFormData({ ...formData, hint: e.target.value })}
                />
              </div>

              <div className="flex items-center justify-between">
                <Label>Active</Label>
                <Switch
                  checked={formData.is_active}
                  onCheckedChange={(checked) => setFormData({ ...formData, is_active: checked })}
                />
              </div>

              <div className="flex justify-end gap-2 pt-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => {
                    setDialogOpen(false);
                    resetForm();
                  }}
                >
                  <X className="w-4 h-4 mr-2" />
                  Cancel
                </Button>
                <Button type="submit" disabled={saving}>
                  {saving ? (
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  ) : (
                    <Save className="w-4 h-4 mr-2" />
                  )}
                  {editingGame ? 'Update' : 'Create'}
                </Button>
              </div>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Label className="text-sm">Filter</Label>
            <Select value={filterType} onValueChange={(v) => setFilterType(v as any)}>
              <SelectTrigger className="w-48">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Types</SelectItem>
                <SelectItem value="trivia">Trivia</SelectItem>
                <SelectItem value="guess_character">Guess Character</SelectItem>
                <SelectItem value="fill_blank">Fill in Blank</SelectItem>
                <SelectItem value="memory_verse">Memory Verse</SelectItem>
              </SelectContent>
            </Select>
            <Button
              size="sm"
              variant="destructive"
              className="ml-2"
              onClick={async () => {
                const count = games.filter(g => filterType === 'all' ? true : g.game_type === filterType).length;
                if (filterType === 'all') {
                  if (!confirm('You have selected "All" — this will delete all questions. Continue?')) return;
                } else {
                  if (!confirm(`Delete ${count} questions of type '${filterType}'? This cannot be undone.`)) return;
                }
                setDeletingFiltered(true);
                try {
                  const q = supabase.from('bible_games').delete();
                  if (filterType !== 'all') q.eq('game_type', filterType);
                  const { error } = await q;
                  if (error) throw error;
                  toast({ title: 'Deleted', description: `Removed ${count} questions.` });
                  await fetchGames();
                } catch (e) {
                  console.error('Error deleting filtered questions:', e);
                  toast({ title: 'Error', description: 'Failed to delete filtered questions', variant: 'destructive' });
                } finally {
                  setDeletingFiltered(false);
                }
              }}
              disabled={deletingFiltered || games.filter(g => filterType === 'all' ? true : g.game_type === filterType).length === 0}
            >
              {deletingFiltered ? <Loader2 className="w-4 h-4 animate-spin" /> : <Trash2 className="w-4 h-4" />}
              <span className="ml-2">Delete Filtered</span>
            </Button>
          </div>
          <div className="text-xs text-muted-foreground">Showing {games.filter(g => filterType === 'all' ? true : g.game_type === filterType).length} questions</div>
        </div>

        {games.filter(g => filterType === 'all' ? true : g.game_type === filterType).map((game) => (
          <Card key={game.id} className="bg-card border-border">
            <CardHeader className="pb-2">
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <span className="text-xs px-2 py-0.5 rounded-full bg-primary/20 text-primary">
                      {game.game_type.replace('_', ' ')}
                    </span>
                    <span className={`text-xs px-2 py-0.5 rounded-full ${
                      game.difficulty === 'easy' ? 'bg-green-500/20 text-green-500' :
                      game.difficulty === 'medium' ? 'bg-yellow-500/20 text-yellow-500' :
                      'bg-red-500/20 text-red-500'
                    }`}>
                      {game.difficulty}
                    </span>
                    {game.bible_story && (
                      <span className="text-xs px-2 py-0.5 rounded-full bg-blue-500/20 text-blue-600 dark:text-blue-400">
                        {game.bible_story}
                      </span>
                    )}
                    {game.testament && (
                      <span className={`text-xs px-2 py-0.5 rounded-full ${
                        game.testament === 'old' 
                          ? 'bg-purple-500/20 text-purple-600 dark:text-purple-400' 
                          : 'bg-amber-500/20 text-amber-600 dark:text-amber-400'
                      }`}>
                        {game.testament === 'old' ? 'OT' : 'NT'}
                      </span>
                    )}
                    {!game.is_active && (
                      <span className="text-xs px-2 py-0.5 rounded-full bg-muted text-muted-foreground">
                        Inactive
                      </span>
                    )}
                  </div>
                  <CardTitle className="text-sm md:text-base font-medium line-clamp-3 break-words">
                    {game.question}
                  </CardTitle>
                </div>
                <div className="flex gap-1 mt-2 sm:mt-0">
                  <Button
                    size="sm"
                    variant="ghost"
                    className="h-8 w-8 sm:h-8 sm:w-8"
                    onClick={() => handleEdit(game)}
                    aria-label="Edit question"
                  >
                    <Pencil className="w-4 h-4" />
                  </Button>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="h-8 w-8 text-destructive hover:text-destructive"
                    onClick={() => handleDelete(game.id)}
                    aria-label="Delete question"
                  >
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent className="pt-0">
              <p className="text-xs sm:text-sm text-muted-foreground break-words">
                <span className="font-medium">Answer:</span> <span className="break-words">{game.correct_answer}</span>
                <span className="mx-1">•</span>
                <span className="font-medium">Points:</span> {game.points}
                {game.bible_reference && (
                  <>
                    <span className="mx-1">•</span>
                    <span className="break-words">{game.bible_reference}</span>
                  </>
                )}
              </p>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
};

export default AdminGameManagement;
