-- Insert Guess the Character questions
INSERT INTO public.bible_games (game_type, question, correct_answer, hint, difficulty, bible_reference, points, options) VALUES
('guess_character', 'Clue 1: I was a shepherd boy.\nClue 2: I killed a giant with a sling and stone.\nClue 3: I became the greatest king of Israel.\nClue 4: I wrote many psalms.', 'David', 'I was described as "a man after God''s own heart"', 'easy', '1 Samuel 17', 10, '["David", "Solomon", "Saul", "Moses"]'),
('guess_character', 'Clue 1: I was thrown into a pit by my brothers.\nClue 2: I was sold into slavery in Egypt.\nClue 3: I interpreted dreams for Pharaoh.\nClue 4: I saved my family during a famine.', 'Joseph', 'I had a coat of many colors', 'easy', 'Genesis 37-50', 10, '["Joseph", "Benjamin", "Jacob", "Judah"]'),
('guess_character', 'Clue 1: I was hidden in a basket as a baby.\nClue 2: I was raised in Pharaoh''s palace.\nClue 3: I led my people out of Egypt.\nClue 4: I received the Ten Commandments on Mount Sinai.', 'Moses', 'I parted the Red Sea', 'easy', 'Exodus 2-20', 10, '["Moses", "Aaron", "Joshua", "Abraham"]'),
('guess_character', 'Clue 1: I was the strongest man who ever lived.\nClue 2: My strength came from my long hair.\nClue 3: I was betrayed by a woman I loved.\nClue 4: I destroyed a temple in my final act.', 'Samson', 'I killed a lion with my bare hands', 'medium', 'Judges 13-16', 15, '["Samson", "Gideon", "David", "Goliath"]'),
('guess_character', 'Clue 1: I was a tax collector before my calling.\nClue 2: Jesus called me to follow Him.\nClue 3: I wrote one of the four Gospels.\nClue 4: I hosted a dinner for Jesus at my house.', 'Matthew', 'I am also called Levi', 'medium', 'Matthew 9:9-13', 15, '["Matthew", "Mark", "Luke", "John"]'),
('guess_character', 'Clue 1: I denied knowing Jesus three times.\nClue 2: Jesus called me the rock.\nClue 3: I walked on water briefly.\nClue 4: I preached on the day of Pentecost.', 'Peter', 'I was a fisherman before becoming a disciple', 'easy', 'Matthew 16:18', 10, '["Peter", "James", "John", "Andrew"]'),
('guess_character', 'Clue 1: I was swallowed by a great fish.\nClue 2: God told me to preach to Nineveh.\nClue 3: I tried to flee from God''s calling.\nClue 4: The city repented after hearing my message.', 'Jonah', 'I spent three days and nights in the fish', 'easy', 'Jonah 1-4', 10, '["Jonah", "Elijah", "Amos", "Hosea"]'),
('guess_character', 'Clue 1: I was a Moabite woman.\nClue 2: I refused to leave my mother-in-law.\nClue 3: I gleaned in the fields of a man named Boaz.\nClue 4: I became an ancestor of Jesus Christ.', 'Ruth', 'I said "Where you go, I will go"', 'medium', 'Ruth 1-4', 15, '["Ruth", "Naomi", "Esther", "Deborah"]'),
('guess_character', 'Clue 1: I was a queen who risked my life for my people.\nClue 2: I was chosen in a beauty contest.\nClue 3: I exposed a plot to destroy the Jews.\nClue 4: A festival is named after me.', 'Esther', 'I was married to King Xerxes', 'medium', 'Esther 1-10', 15, '["Esther", "Ruth", "Deborah", "Rahab"]'),
('guess_character', 'Clue 1: I built an ark according to God''s instructions.\nClue 2: I gathered animals two by two.\nClue 3: I survived a great flood with my family.\nClue 4: God made a covenant with me symbolized by a rainbow.', 'Noah', 'I was 600 years old when the flood came', 'easy', 'Genesis 6-9', 10, '["Noah", "Abraham", "Adam", "Enoch"]');